### ISSUE TITLE
Ressource load failed using npm start

### ISSUE THREAD

**Issue by DblK** [thomas-barthelemy/electron-angular-boilerplate#2]
Just after cloning the repo I launched the command `npm start` and it launched the app in electron.
Nevertheless, I have a error in the console :
`file:///[...]/scripts/app.angular.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND`

This problem isn't showing when I use `grunt build` and launch the "dist" app.

Could you fix this or tell me what to do?

FYI: I'm building on windows.

**Comment by thomas-barthelemy** [comment]
This is expected, and as you said won't happen once built.
The `app.angular.min.js` is a compilation of all the other JS files that is created during the build,
to ease the debugging this file is not created when simply running electron with npm start and the app will be loading the `.js` files independently instead.

**Comment by thomas-barthelemy** [comment]
I ended up switching grunt task so that this unneeded file during dev wouldn't be loaded.
